name: assignment_50walletui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\Group 4.png
    - assets\images\Group 4 (1).png
    - assets\images\Group 10.png   
    - assets\images\Frame 7.png
    - assets\images\Frame 6.png
    - assets\images\Frame 5.png
    - assets\images\Group 9.png
