name: assignment48fashion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets\images\img1.png
    - assets\images\img2.png
    - assets\images\img3.png
    - assets\images\img4.png
    - assets\images\img5.png
    - assets\images\img6.png  
    - assets\images\Ellipse 14.png
    - assets\images\Ellipse 15.png
    - assets\images\Ellipse 16.png
    - assets\images\img7.png
    - assets\images\img8.png
    - assets\images\g13.png
    - assets\images\Group 10.png
    - assets\images\Rectangle 121.png
    - assets\images\Vector.png
    - assets\images\visa.png
    - assets\images\american-express.png