name: assignment_49cycle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  action_slider: ^0.7.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\image 6.png
    - assets\images\pngwing.png
    - lib\Screens\homes.dart
    - assets\images\pngwing_.png
    - assets\images\pngwing (5).png
    - assets\images\pngwing (4).png
    - assets\images\pngwing (2).png
    - assets\images\pngwing (1).png
    - assets\images\image 4.png
    - assets\images\image 3.png
    - assets\images\image 2.png
    - assets\images\image 1.png
    - assets\images\house.png
    - assets\images\wallet-add.png
    - assets\images\user.png
    - assets\images\shopping-bag.png
    - assets\images\pngwingp.png
    - assets\images\img 3.png
    - assets\images\img 6.png
    - assets\images\png.png
    


 
