name: assignment_47petcareapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\Brandmark Logo.png
    - assets\images\Frame 2016.png
    - assets\images\Frame 2061 (1).png
    - assets\images\Frame 2061 (2).png
    - assets\images\Frame 2061 (3).png
    - assets\images\Frame 2061 (4).png
    - assets\images\Frame 2061.png
    - assets\images\image (1).png
    - assets\images\image (2).png
    - assets\images\image (3).png
    - assets\images\image (4).png
    - assets\images\image (5).png
    - assets\images\image (6).png
    - assets\images\image (7).png
    - assets\images\image (8).png
    - assets\images\image (9).png
    - assets\images\image (10).png
    - assets\images\image (11).png
    - assets\images\image (12).png
    - assets\images\image (13).png
    - assets\images\image (14).png
    - assets\images\image (15).png
    - assets\images\image (16).png
    - assets\images\image (17).png
    - assets\images\image (18).png
    - assets\images\image (19).png
    - assets\images\image (20).png
    - assets\images\image.png
    - assets\images\Pet Shop (1).png
    - assets\images\Pet Shop (2).png
    - assets\images\Pet Shop (3).png
    - assets\images\Pet Shop (4).png
    - assets\images\Pet Shop.png
    - assets\images\splash.png
    - assets\images\image..png
    - assets\images\image@2x.png
    - assets\images\image_.png
    - assets\images\fi_map.png
    - assets\images\Pet Shop.png
    - assets\images\Frame 2117.png